import json
import re

dashboard_hi = {
    'Receivables aging past 45 days': '45 दिनों से अधिक के प्राप्य',
    'Two key clients delayed payment cycles': 'दो प्रमुख ग्राहकों ने भुगतान चक्र में देरी की',
    'Introduce a 2% early-payment discount and automate reminders': '2% शीघ्र-भुगतान छूट पेश करें और रिमाइंडर स्वचालित करें',
    'Inventory concentration risk': 'इन्वेंटरी एकाग्रता जोखिम',
    '68% of stock value sits in 3 SKUs': '68% स्टॉक मूल्य 3 SKU में है',
    'Diversify purchasing across 2 additional suppliers': '2 अतिरिक्त आपूर्तिकर्ताओं में खरीद में विविधता लाएं',
    'Rising customer acquisition cost': 'बढ़ती ग्राहक अधिग्रहण लागत',
    'Ad spend up 30% with flat conversion': 'स्थिर रूपांतरण के साथ विज्ञापन खर्च में 30% की वृद्धि',
    'Reallocate budget toward referral incentives': 'रेफरल प्रोत्साहन की ओर बजट पुनः आवंटित करें',
    'Thin cash buffer': 'कम नकद बफर',
    'Average 9 days of operating expenses on hand': 'हाथ में औसतन 9 दिनों का परिचालन खर्च',
    'Set aside 5% of weekly revenue into a reserve account': 'साप्ताहिक राजस्व का 5% आरक्षित खाते में अलग रखें',
    'Manual attendance tracking': 'मैनुअल उपस्थिति ट्रैकिंग',
    'Paper registers slow payroll processing': 'कागजी रजिस्टर पेरोल प्रसंस्करण को धीमा करते हैं',
    'Adopt a low-cost biometric or app-based tracker': 'कम लागत वाला बायोमेट्रिक या ऐप-आधारित ट्रैकर अपनाएं',
    'Underused loyalty program': 'कम उपयोग किया गया वफादारी कार्यक्रम',
    'Only 12% of repeat customers enrolled': 'केवल 12% दोहराने वाले ग्राहक नामांकित हैं',
    'Prompt enrollment at checkout with a small incentive': 'छोटे प्रोत्साहन के साथ चेकआउट पर नामांकन के लिए प्रेरित करें',
    'Root cause': 'मूल कारण',
    'Action': 'कार्रवाई',
    'Impact': 'प्रभाव',
    'This recommendation was generated by the AI engine based on current market trends and your internal data to mitigate financial distress.': 'यह सिफारिश वर्तमान बाजार के रुझानों और आपके आंतरिक डेटा के आधार पर वित्तीय संकट को कम करने के लिए AI इंजन द्वारा उत्पन्न की गई थी।'
}

dashboard_te = {
    'Receivables aging past 45 days': '45 రోజులు దాటిన స్వీకరించదగినవి',
    'Two key clients delayed payment cycles': 'ఇద్దరు కీలక క్లయింట్లు చెల్లింపు సైకిళ్లను ఆలస్యం చేశారు',
    'Introduce a 2% early-payment discount and automate reminders': '2% ముందస్తు చెల్లింపు తగ్గింపును ప్రవేశపెట్టండి మరియు రిమైండర్‌లను ఆటోమేట్ చేయండి',
    'Inventory concentration risk': 'ఇన్వెంటరీ ఏకాగ్రత ప్రమాదం',
    '68% of stock value sits in 3 SKUs': 'స్టాక్ విలువలో 68% 3 SKUలలో ఉంది',
    'Diversify purchasing across 2 additional suppliers': 'అదనపు 2 సరఫరాదారుల ద్వారా కొనుగోళ్లను వైవిధ్యపరచండి',
    'Rising customer acquisition cost': 'పెరుగుతున్న కస్టమర్ సముపార్జన వ్యయం',
    'Ad spend up 30% with flat conversion': 'ఫ్లాట్ మార్పిడితో యాడ్ ఖర్చు 30% పెరిగింది',
    'Reallocate budget toward referral incentives': 'రిఫరల్ ప్రోత్సాహకాల వైపు బడ్జెట్‌ను మళ్లీ కేటాయించండి',
    'Thin cash buffer': 'తక్కువ నగదు బఫర్',
    'Average 9 days of operating expenses on hand': 'చేతిలో సగటున 9 రోజుల ఆపరేటింగ్ ఖర్చులు',
    'Set aside 5% of weekly revenue into a reserve account': 'వారపు రాబడిలో 5% రిజర్వ్ ఖాతాలో పక్కన పెట్టండి',
    'Manual attendance tracking': 'మాన్యువల్ హాజరు ట్రాకింగ్',
    'Paper registers slow payroll processing': 'పేపర్ రిజిస్టర్లు పేరోల్ ప్రాసెసింగ్‌ను నెమ్మదిస్తాయి',
    'Adopt a low-cost biometric or app-based tracker': 'తక్కువ ఖర్చుతో కూడిన బయోమెట్రిక్ లేదా యాప్ ఆధారిత ట్రాకర్‌ని అడాప్ట్ చేయండి',
    'Underused loyalty program': 'తక్కువగా ఉపయోగించబడిన లాయల్టీ ప్రోగ్రామ్',
    'Only 12% of repeat customers enrolled': '12% మంది రిపీట్ కస్టమర్‌లు మాత్రమే నమోదు చేసుకున్నారు',
    'Prompt enrollment at checkout with a small incentive': 'చిన్న ప్రోత్సాహకంతో చెక్‌అవుట్ వద్ద ప్రాంప్ట్ నమోదు',
    'Root cause': 'మూల కారణం',
    'Action': 'చర్య',
    'Impact': 'ప్రభావం',
    'This recommendation was generated by the AI engine based on current market trends and your internal data to mitigate financial distress.': 'ఆర్థిక ఇబ్బందులను తగ్గించడానికి ప్రస్తుత మార్కెట్ పోకడలు మరియు మీ అంతర్గత డేటా ఆధారంగా AI ఇంజిన్ ద్వారా ఈ సిఫార్సు రూపొందించబడింది.'
}

def main():
    with open('locales/hi/translation.json', 'r', encoding='utf-8') as f:
        hi_dict = json.load(f)
        
    with open('locales/te/translation.json', 'r', encoding='utf-8') as f:
        te_dict = json.load(f)
        
    hi_dict.update(dashboard_hi)
    te_dict.update(dashboard_te)
    
    with open('locales/hi/translation.json', 'w', encoding='utf-8') as f:
        json.dump(hi_dict, f, indent=2, ensure_ascii=False)
        
    with open('locales/te/translation.json', 'w', encoding='utf-8') as f:
        json.dump(te_dict, f, indent=2, ensure_ascii=False)
        
    print("Dashboard translations added!")

if __name__ == '__main__':
    main()
